### PR TITLE
Add Hungarian language

### PR DESCRIPTION
**Pull request by djlancelot**
Draft PR, added for visibility and initial feedback. Around 396000 sentences extracted initially.

### CODE REVIEW

**Comment by djlancelot** [comment]
@mmihaltz, I started this PR it should automatically collect a couple 100 thousand sentences for Common-Voice. I'd appreciate your help for validation.

**Comment by MichaelKohler** [comment]
Hi, thanks for creating this. The rules file looks good to me so far. Here are the remaining two questions:

* How did you create the blocklist file?
* Get at least 3 different native speakers (ideally linguists) to review a random sample of 100-500 sentences and estimate the average error ratio and comment (or link their comment) in the PR.

You can find a generated sample file for the second question at https://github.com/Common-Voice/cv-sentence-extractor/pull/121/checks?check_run_id=893250641 (Artifacts button on the top right)

**Comment by djlancelot** [comment]
### How many sentences did you get at the end?
362420 sentences were extracted in the end.
### How did you create the blocklist?
It has 3 parts:
- a manual list of entries based on the frequent entries in the word usage list
- all words were stemmed and the occurrence count was summed up to the stem of the word.
-- All stems and their occurrences with fewer than 12 count were removed.
-- All stems and their occurrences with more than 12 count and lower than 36 count with fewer than 4 occurence was removed too.
### Get at least 3 different native speakers (ideally linguistics) to review a random sample of 100-500 sentences and estimate the average error ratio and comment (or link their comment) in the PR.
Working on this...

**Comment by djlancelot** [comment]
### How many sentences did you get at the end?
312 630 sentences were extracted in the end.
### How did you create the blocklist?
It has 3 parts:
* a manual list of entries based on the frequent entries in the word usage list
* all words were stemmed and the occurrence count was summed up to the stem of the word.
  - All stems and their occurrences with fewer than 80 count were removed.
  - All stems and their occurrences with more than 80 count and lower than 100 count with fewer than 4 occurence were removed too.
### Get at least 3 different native speakers (ideally linguistics) to review a random sample of 100-500 sentences and estimate the average error ratio and comment (or link their comment) in the PR.

- TODO
- My wife's initial measurement 99%
- My initial measurement was 97%

### Conclusion
Waiting for 3rd reviewer, I will be sharing the spreadsheet when done.

**Comment by djlancelot** [comment]
@MichaelKohler, thanks for your patience. I shared the spreadsheet with a couple of people and got their ratings. I updated the previous comment according to their answers.

**Review by MichaelKohler — APPROVED** [review]
Thanks, that looks good to me. I will wait with merging as I first want to check an error in the automatic export generation.

**Pull request merged**
