### PR TITLE
Add Georgian rules and blacklist

### PR DESCRIPTION
**Pull request by AG12r**
-     How many sentences did you get at the end?
~125000
-     How did you create the blacklist file?
Filtering out words with < 4 repetitions
-     What is the error ratio?
4-5%. Many of them are verb less opening (descriptive) sentences of Wikipedia articles.
-     Get at least 3 different native speakers (ideally linguistics) to review a random sample of 100-500 sentences and estimate the average error ratio and comment (or link their comment) in the PR.
For review, 3 x 100 randomly selected sentences are avaiable here:
https://gist.github.com/AG12r/f25a9c7774730ae8d5b9b452882f0dd6

### CODE REVIEW

**Comment by MichaelKohler** [comment]
Thanks, looks good to me from the technical side.

> Many of them are verb less opening (descriptive) sentences of Wikipedia articles.

Can you elaborate on that? I'm not sure I understand this.

**Comment by AG12r** [comment]
I mean incomplete sentences (without a verb), like this:
`List of cities in Australia by population.`

@MichaelKohler

**Comment by MichaelKohler** [comment]
I guess it would be nice to have full sentences, but I'd say it's not that bad if not. And if we count them as bad and it's still an error rate that is below what we want, that's fine.

**Comment by MichaelKohler** [comment]
Can I ask you to do the following, to make sure you can profit from the [automatic sample extraction](https://discourse.mozilla.org/t/scraper-automatic-sample-sentences-extracted-in-pull-request/55217) we just introduced?

* Update your branch with the latest code from the `master` branch
* Rename `src/rules/georgian.toml` to `src/rules/ka.toml`
* Rename `src/rules/disallowed_words/georgian.toml` to `src/rules/disallowed_words/ka.toml`

Also note that the local command for extraction will now be:

```
cargo run -- extract -l ka -d path/to/files
```

Happy to answer any question you may have and thanks for your efforts!

Also, did you have any luck finding reviewers?

**Comment by AG12r** [comment]
@MichaelKohler 
> Update your branch with the latest code from the master branch

It's done, but with an error: "stream did not contain valid UTF-8". Is the problem from my side?

> Also, did you have any luck finding reviewers?

Yes, I contacted with another cv contributor and perhaps he can help.

Thanks.

**Comment by MichaelKohler** [comment]
I'll have a look, most probably not your fault.

**Comment by MichaelKohler** [comment]
> It's done, but with an error: "stream did not contain valid UTF-8". Is the problem from my side?

I'm pretty sure this is not your fault. I will dive deeper into it this week.

**Comment by MichaelKohler** [comment]
I can't really reproduce this. A subsequent run in here was green as well. Let's go with this for now and keep an eye on it. You can find the check (and the artifact with the extracted sentences) at https://github.com/Common-Voice/cv-sentence-extractor/runs/496154280?check_suite_focus=true

**Comment by AG12r** [comment]
> You can find the check (and the artifact with the extracted sentences) at 
> https://github.com/Common-Voice/cv-sentence-extractor/runs/496154280?check_suite_focus=true

I've reviewed it and the quality is good as expected.
Also, is the "opposite characters" already implemented? Can I add quotation marks to the rules file?

@MichaelKohler

**Comment by MichaelKohler** [comment]
Yes, "opposite characters" is implemented as described in the README.

**Comment by AG12r** [comment]
> Yes, "opposite characters" is implemented as described in the README.

Thanks, I'll add it then.

> Also, did you have any luck finding reviewers?

Update: Two volunteers have reviewed 200 random sentences. Their comments and the revised texts are available here:
https://gist.github.com/AG12r/f25a9c7774730ae8d5b9b452882f0dd6#gistcomment-3206730

- There were 4 spelling errors in the first segment. 
- The second part has been reviewed by linguistic expert and it has 4 spelling, 1 stylistic and 11 punctuation (missing commas) errors.

Is this error rate (4/100) acceptable?

I can increase the number of repetitions to create the blacklist, but in Georgian, there are many words containing prefixes, suffixes, infixes and they have low repetition rates. So, a lot of potentially valid sentences will be discarded.

**Comment by MichaelKohler** [comment]
> Update: Two volunteers have reviewed 200 random sentences. Their comments and the revised texts are available here:
https://gist.github.com/AG12r/f25a9c7774730ae8d5b9b452882f0dd6#gistcomment-3206730
There were 4 spelling errors in the first segment.
The second part has been reviewed by linguistic expert and it has 4 spelling, 1 stylistic and 11 punctuation (missing commas) errors.
Is this error rate (4/100) acceptable?

@nukeador up to you to decide, I'd argue that comma errors are negligible and therefore this is under the desired error rate?

**Comment by nukeador** [comment]
Commas should be fine

**Comment by MichaelKohler** [comment]
@nukeador to be sure, therefore this is approved by you and we can merge this?

**Comment by nukeador** [comment]
4% is OK

**Pull request merged**
